modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT License"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''
LavaWalker generates obsidians as you walk over
lava. Generated Obsidians melt into lava through
crying obsidians over time.
'''
[[dependencies.lava_walker]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies.lava_walker]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
